### ISSUE TITLE
Source code request

### ISSUE THREAD

**Issue by wangyePHD** [Colin97/OpenShape_code#1]
Thanks for your nice work. Can you share your code to me? 
yewang22@mails.jlu.edu.cn

**Comment by eliphatfs** [comment]
We are still doing final cleaning up, and the code will be made available soon.

**Comment by wangyePHD** [comment]
Thanks for your kind reply.  I just want to test the performance of your model. If you release the source code, I think it will motivate me very much.

**Comment by eliphatfs** [comment]
The inference code is now available at the demo.
https://huggingface.co/OpenShape/openshape-demo-support
