### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by StellarCheng** [Colin97/OpenShape_code#10]
Hello author, the guidance you provided "pip install -U git+https://github.com/NVIDIA/MinkowskiEngine" is not working for installation on the latest GPU A6000 with CUDA 12.1. Is there any way to install MinkowskiEngine on these new machines? Thanks!

**Comment by Colin97** [comment]
No idea... Similar problems reported here: https://github.com/NVIDIA/MinkowskiEngine/issues/543.

**Comment by StellarCheng** [comment]
> No idea... Similar problems reported here: [NVIDIA/MinkowskiEngine#543](https://github.com/NVIDIA/MinkowskiEngine/issues/543).

So sad, So, is it means I need to run the code in a previous vision of CUDA? May I ask what GPU and CUDA versions you used in your project? Thanks

**Comment by Colin97** [comment]
You can use the PointBERT backbone which doesn't need [MinkowskiEngine](https://github.com/NVIDIA/MinkowskiEngine).

We have tired various GPUs (e.g., A100, A10, RTX, etc) and CUDA versions (e.g., 11.3)

**Comment by StellarCheng** [comment]
> You can use the PointBERT backbone which doesn't need [MinkowskiEngine](https://github.com/NVIDIA/MinkowskiEngine).
> 
> We have tired various GPUs (e.g., A100, A10, RTX, etc) and CUDA versions (e.g., 11.3)

Thanks for your quick reply~

**Comment by eliphatfs** [comment]
The demo include various models for different tasks (pointbert-vitg14/l14/b14-rgb), but they are all PointBERT models.

**Comment by StellarCheng** [comment]
> The demo includes various models for different tasks (pointbert-vitg14/l14/b14-rgb), but they are all PointBERT models.

Thanks!

**Comment by Colin97** [comment]
> > The demo includes various models for different tasks (pointbert-vitg14/l14/b14-rgb), but they are all PointBERT models.
> 
> Thanks! Is there any example code using pointbert-vitg14/l14/b14-rgb to extract point clouds embedding from glb/obj file? Current example code is based on [MinkowskiEngine](https://github.com/NVIDIA/MinkowskiEngine)

Please refer to the [demo code](https://huggingface.co/spaces/OpenShape/openshape-demo/blob/b9f9a149287df77bc1c9babadf0e3fd86bc540c0/app.py#L160).

**Comment by rayryeng** [comment]
Hello - I just wanted to mention that the fix linked in the thread posted (https://github.com/NVIDIA/MinkowskiEngine/issues/543#issuecomment-1773458776) fixed the problem for me. The extra complication is that I'm also installing this all in a Docker container, so I used a Docker directive to insert the necessary headers in the required files, then build it. This works with PyTorch 2.1.0, CUDA 12.1 with the NVIDIA image as `nvidia/cuda:12.1.1-devel-ubuntu20.04`

For posterity:

```
RUN git clone https://github.com/NVIDIA/MinkowskiEngine.git /tmp/MinkowskiEngine \
    && cd /tmp/MinkowskiEngine \
    && sed -i '31i #include <thrust/execution_policy.h>' ./src/convolution_kernel.cuh \
    && sed -i '39i #include <thrust/unique.h>\n#include <thrust/remove.h>' ./src/coordinate_map_gpu.cu \
    && sed -i '38i #include <thrust/execution_policy.h>\n#include <thrust/reduce.h>\n#include <thrust/sort.h>' ./src/spmm.cu \
    && sed -i '38i #include <thrust/execution_policy.h>' ./src/3rdparty/concurrent_unordered_map.cuh \
    && python setup.py install --force_cuda --blas=openblas \
    && cd - \
    && rm -rf /tmp/MinkowskiEngine
```

If you don't want to use Docker, this should work by just removing `RUN` and doing this in your native environment. Thanks!
