### ISSUE TITLE
Why use the relative position encoding

### ISSUE THREAD

**Issue by yifliu3** [Colin97/OpenShape_code#12]
Hi, 

I noticed that you have used the relative position of centroids as the input of the position encoding:
`entroid_delta = centroids.unsqueeze(-1) - centroids.unsqueeze(-2)`
may I know the reason to use relative encoding rather the commonly used absolution position encoding

**Comment by eliphatfs** [comment]
I think this is common since PointNet++. This makes the patches independent of the absolute position so the network can embed it more generalizably.
