### ISSUE TITLE
i'm confusing about the text feature  with prompt_avg   

### ISSUE THREAD

**Issue by alanzhangcs** [Colin97/OpenShape_code#14]
Thanks for your great work!  I'm wondering could you release the  generation process of text prompt_avg  feature ?
For example prompt template ?

**Comment by Colin97** [comment]
We follow https://github.com/salesforce/ULIP/blob/main/data/templates.json, to convert each category name to 64 sentences, and calculate the CLIP embedding for each sentence and then take their average as the embedding for the category name.

**Comment by alanzhangcs** [comment]
I got it. Thanks for your reply!
