### ISSUE TITLE
About Custom Mesh Data Preprocessing

### ISSUE THREAD

**Issue by kizum** [Colin97/OpenShape_code#16]
Great work! Thanks for your kindly sharing this project with us!

Based on your work, I want to run some shape retrieval demo on my custom mesh data (just assume they are some .obj files). I have noticed that the whole project is based on the point cloud representation. As the paper and repo mentioned, I think I should sample the mesh file into a point clouds file containing 10000 points and align the gravity axis of the mesh. 

However, I am not very sure about the preprocessing details. Could you please give me some hints or provide some example codes (maybe some codes when you process the .glb file in the objaverse)?

Thanks!

**Comment by Junking1** [comment]
same question +1

**Comment by Colin97** [comment]
Please refer to the code [here](https://huggingface.co/OpenShape/openshape-demo-support/blob/24cb86cbc04d4e2361746c7c62e1da915dbfc697/openshape/demo/misc_utils.py#L115).

**Comment by kizum** [comment]
> Please refer to the code [here](https://huggingface.co/OpenShape/openshape-demo-support/blob/24cb86cbc04d4e2361746c7c62e1da915dbfc697/openshape/demo/misc_utils.py#L115).

Thanks a lot!

**Comment by kizum** [comment]
> Please refer to the code [here](https://huggingface.co/OpenShape/openshape-demo-support/blob/24cb86cbc04d4e2361746c7c62e1da915dbfc697/openshape/demo/misc_utils.py#L115).

Hi, sorry for bother again. In the git repo and this model page: https://huggingface.co/OpenShape/openshape-demo-support, I find that you have mentioned that the gravity axis for G14 model is z-axis, and for B32/L14 is y-axis.

In the src/example.py file, the script evaluate the similarity between the demo/owl.ply file and some images/texts. If I have no mistake, the owl.ply file should be a y-gravity-axis point cloud file, like showed in meshlab:
 
![image](https://github.com/Colin97/OpenShape_code/assets/27687088/e6aa1952-b38d-4137-beb6-231847ea163b)

And the output similarity score is like: 
![image](https://github.com/Colin97/OpenShape_code/assets/27687088/94393075-d5b4-473f-93b5-83833e3c42f9)

So, in my mind, if I convert the owl.py into a z-gravity-axis point cloud file, the score should be higher and better. After conversion, the point cloud looks like:
![image](https://github.com/Colin97/OpenShape_code/assets/27687088/a3ebbbbf-99ae-4a20-a740-5b7bb1139a66)

However, when I evaluate the similarity on the new point clouds, the score get lower. 
![image](https://github.com/Colin97/OpenShape_code/assets/27687088/40b02748-d12d-4e28-927a-6acf7e42e375)

Is there anything wrong, or this is just right?

**Comment by Colin97** [comment]
Hi, sorry for the late reply.

In our data loader, we already switched the gravity axis by default (see [here](https://github.com/Colin97/OpenShape_code/blob/a6ea4dbe0a2d68b397eec4ac028c9d176dd6d62f/src/example.py#L27)). So there is no need to change the ply file
