### ISSUE TITLE
Few-shot linear probing implementation ? 

### ISSUE THREAD

**Issue by alanzhangcs** [Colin97/OpenShape_code#17]
Hi, thanks for your great work! I'm wondering that could you release your implementation details of your Few-shot linear probing experiment ?

**Comment by kaimingkuang** [comment]
Our few-shot implementation follows closely to the one in 2D CLIP. Given that features of all 3D shapes in the test dataset are extracted, we randomly choose N samples from each category in the test data and use these features to train a logistic regression model. We simply use [scikit-learn's Logistic Regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) with LBFGS solver, as in 2D CLIP. Next, we evaluate the trained logistic model on the rest of the test dataset. This process is repeated 10 times and we take the average performance.
