### ISSUE TITLE
About the code to render images from point cloud for objaverse

### ISSUE THREAD

**Issue by ganchaofan0000** [Colin97/OpenShape_code#21]
Hi,
It is a great job. I am really interested in it. Could you provide the code of rendering 12 images from point cloud for objaverse.
Thanks!

**Comment by Colin97** [comment]
We render the mesh instead of the point cloud. Please refer to the [code](https://github.com/Colin97/OpenShape_code/blob/d0a86371940511276f58e026a987e0fd0fd45d7e/render_single_glb.py#L1)
