### ISSUE TITLE
Can you provide the code for this visualization?

### ISSUE THREAD

**Issue by zzy994491827** [Colin97/OpenShape_code#22]
![image](https://github.com/Colin97/OpenShape_code/assets/43195646/3e7f84da-39b8-478d-84dc-fec70bec61db)

**Comment by zzy994491827** [comment]
![Uploading newplot.png…]()

**Comment by eliphatfs** [comment]
https://huggingface.co/OpenShape/openshape-demo-support/blob/main/openshape/demo/misc_utils.py#L152
