### ISSUE TITLE
render imgs file is incomplete

### ISSUE THREAD

**Issue by yanx57** [Colin97/OpenShape_code#27]
Hello, I downloaded the render images file,but most compressed files such as 3D-FUTURE.targz can not be successfully uncompress, because it can not find EOF.So, i think the compressed files are not complete ..Can you check the compressed files of render images or  provide the site where we can download the mesh(glb files) of the four 3D dataset such that we can use your render script?

**Comment by eliphatfs** [comment]
cannot find eof usually means your internet is not good and the files are not correctly downloaded

**Comment by yanx57** [comment]
> cannot find eof usually means your internet is not good and the files are not correctly downloaded

Ok,but I can not find Objaverse_12.tar.gz in rendered_images

**Comment by eliphatfs** [comment]
it is misuploaded to the root directory. sorry for the inconvenience.

**Comment by eliphatfs** [comment]
https://huggingface.co/datasets/OpenShape/openshape-training-data/blob/main/Objaverse_12.tar.gz

**Comment by yanx57** [comment]
ok,thanks
