### ISSUE TITLE
 scaling up strategy

### ISSUE THREAD

**Issue by Wolfwjs** [Colin97/OpenShape_code#3]
Thank you so much for such a great job! I have noticed from your paper that scaling up has played a very important role. 

May I ask what are the model parameters of SparseConv & PointBERT after scaling up and what is the scaling strategy in detail ？

**Comment by Colin97** [comment]
Hi, thanks for your attention. Please refer to the supplementary materials for the details of scaling strategy (section 6.4). 

For the model parameters of SparseConv & PointBERT, please check our code. Here are the commands for the two backbones:

python3 src/main.py --trail_name spconv_all 
python3 src/main.py --trail_name pointbert_all model.name=PointBERT model.scaling=4 model.use_dense=True training.lr=0.0005 training.lr_decay_rate=0.967
