### ISSUE TITLE
Code for point cloud-conditioned image generation

### ISSUE THREAD

**Issue by auniquesun** [Colin97/OpenShape_code#32]
@Colin97 @eliphatfs Thanks for sharing the paper. It is a great work!

I noticed you mentioned the point cloud-conditioned image generation and you also provided visualizations of the generate images. It's pretty cool. And I think it is interesting direction to deserve further exploration. 

My question is can you provide the code related to this part? Thanks.

Looking forward to you reply!

**Comment by eliphatfs** [comment]
You can find it in the demo code. https://huggingface.co/OpenShape/openshape-demo-support/blob/main/openshape/demo/sd_pc2img.py

**Comment by auniquesun** [comment]
Thanks for your reply.

**Comment by auniquesun** [comment]
> You can find it in the demo code. https://huggingface.co/OpenShape/openshape-demo-support/blob/main/openshape/demo/sd_pc2img.py

@eliphatfs @Colin97 Since this code is used for online demo and the demo is out of order now. I have some questions related to calling the core function `pc_to_image`, e.g., what values do I need to pass in, such as for 

    - `prompt`, 
    - `noise_level`, 
    - `width`,
    - `height`,
    - `cfg_scale`, 
    - `num_steps`, 
    - `callback`.

Could you please provide the default values you used in the demo so that other can reproduce the point cloud conditioned image generation? 

Thanks.
