### ISSUE TITLE
Normal Vector Information of OpenShape Assets

### ISSUE THREAD

**Issue by Gofinge** [Colin97/OpenShape_code#33]
Hi @Colin97 @eliphatfs ,

Thanks for your excellent work! It is really convenient to use well-organized 3D object assets with OpenShape. As a normal vector is usually good for perception and can be easily obtained with CAD or RGB-D sequence, it would be really helpful if you could also process one version of OpenShape with a normal vector?

Best,
Xiaoyang

**Comment by Colin97** [comment]
You can calculate the mesh normals with off-the-shelf tools like Open3D's compute_vertex_normals().

**Comment by Gofinge** [comment]
One problem is that compute_vertex_ normals are accurate with the original mesh yet imprecise with the point cloud. Might need to make some adaptations to your preprocessing code. But that’s fine, I can write one from scratch.
