### ISSUE TITLE
Total training epochs

### ISSUE THREAD

**Issue by suwoongleekor** [Colin97/OpenShape_code#34]
Thank you for your great work and sharing the code. 

I'm curious about the training epoch to reproduce your experimental results. 
The paper doesn't seem to list the training epoch you used, and the max_train_epoch=10000 in configs/train.yaml seems to be excessively long. 

Can you tell me the training epochs you used for All, NO-LVIS, and ShapeNet_only?

**Comment by Colin97** [comment]
Sorry, I forgot the training epochs. However, as mentioned in the supp: "We train the model on a single A100 GPU with a batch size of 200. Since we precache the text and image CLIP embeddings of all shapes, the training is greatly accelerated and takes about 300 A100 hours for convergence."

**Comment by suwoongleekor** [comment]
Thank you for your reply!
