### ISSUE TITLE
how to easily retrieve the desired Shape files (Mesh) of objects using your code?

### ISSUE THREAD

**Issue by StellarCheng** [Colin97/OpenShape_code#5]
Hello author, thank you for your excellent work. I would like to know how to easily retrieve the desired Mesh files of objects using your code. For example, I only want to retrieve the top N Shape files that match the description of 'a vintage American sports car' based on text. Could you please guide me on how to obtain the corresponding Shape files? Thank you

**Comment by eliphatfs** [comment]
If you are not running this in a large volume, you may try the online demo. By clicking on links below results you will jump to a dataset page where you can download them.

If you want to do it for a large set of descriptions, you will need to download the [embeddings](https://huggingface.co/datasets/OpenShape/openshape-objaverse-embeddings). You can check the relevant code [here](https://huggingface.co/OpenShape/openshape-demo-support/blob/main/openshape/demo/retrieval.py) on how to use them to retrieve results. You can download from the `glb` key in the returned entries (an example of returned entry is pasted in the code comments) at this uri: `https://huggingface.co/datasets/allenai/objaverse/resolve/main/{glb}`.

**Comment by StellarCheng** [comment]
> 

Thank you for your response. In this code snippet, CLIP is not used to calculate the embeddings. Could you please clarify which version of CLIP you are referring to?

**Comment by Colin97** [comment]
Yes, you can use the OpenCLIP (ViT-bigG-14) for the text and image embedding.

**Comment by StellarCheng** [comment]
> Yes, you can use the OpenCLIP (ViT-bigG-14) for the text and image embedding.

Thanks, that's clear~
