### ISSUE TITLE
About inputs to ModelNet

### ISSUE THREAD

**Issue by junshengzhou** [Colin97/OpenShape_code#6]
Hi, 
Thanks for your great job! I have a question on the inputs to ModelNet. In the paper, you mentioned that for ModelNet, the input is 10k points without color. But in the code, the `self.use_color = config.dataset.use_color` in ModelNetTest is set to True, according to the config file. I wonder if it is a mistake or if I miss something. Thanks for your time!

Best,

**Comment by Colin97** [comment]
Yes, we set use_color to True in config in order to unify the network input (6xn). The color of ModelNet shapes are set to a constant of 0.4.
