### ISSUE TITLE
Issues about channel of xyz in example.py

### ISSUE THREAD

**Issue by Holmes-GU** [Colin97/OpenShape_code#7]
Hi, thanks for your codes. I have tried to run python src/examples. However, it returns 'RuntimeError: Given groups=1, weight of size [64, 9, 1, 1], expected input[1, 10, 64, 384] to have 9 channels, but got 10 channels instead', deriving from self.mlp of function 'PointNetSetAbstraction' in modes/pointnet_util.py. The source maybe lie in the channel of xyz (4 in example.py). Is there any solutions? 

Thank you very much.

**Comment by eliphatfs** [comment]
Hi. I am a little confused why you are seeing 4 channels for xyz.
![image](https://github.com/Colin97/OpenShape_code/assets/23738781/00b6b573-c7c6-49c2-8dde-b694197e653d)
Mine has 3.

**Comment by Holmes-GU** [comment]
Hi, in this function in the example.py, the xyzzy is processed by ME.utils.batched_coordinates(), therefore, the channel becomes 4.
<img width="978" alt="image" src="https://github.com/Colin97/OpenShape_code/assets/55798572/acc1f2ef-0c00-4c50-8162-38c1840ca11c">

**Comment by Holmes-GU** [comment]
> Hi. I am a little confused why you are seeing 4 channels for xyz.
> ![image](https://user-images.githubusercontent.com/23738781/252928446-00b6b573-c7c6-49c2-8dde-b694197e653d.png)
> Mine has 3.

Hi, I follow 'python3 src/example.py' for quick start. In example.py, the xyz is processed by ME.utils.batched_coordinates(), therefore, the channel becomes 4, as shown below.
<img width="978" alt="image" src="https://github.com/Colin97/OpenShape_code/assets/55798572/e9ab227f-8fd5-4ffc-a4b5-f1b92a721f2f">

**Comment by Colin97** [comment]
Hi, which checkpoint are you using? The example.py is for spconv. If you are using a pointbert checkpoint, some modifications are needed. Sorry for the confusion.

**Comment by Holmes-GU** [comment]
> Hi, which checkpoint are you using? The example.py is for spconv. If you are using a pointbert checkpoint, some modifications are needed. Sorry for the confusion.

I have changed the backbone to pointbert and model.scaling=4 with model.use_dense=True. Would you like to give exact modifications? Thanks.
<img width="1071" alt="image" src="https://github.com/Colin97/OpenShape_code/assets/55798572/f01e340d-e0fd-4d41-b996-3e2e397511bd">

**Comment by Colin97** [comment]
Hi, please refer to the codes:

https://github.com/Colin97/OpenShape_code/blob/26cf8d16551368f8f1e8e3801cbfb629b6157a03/src/train.py#L101C18-L101C18

https://github.com/Colin97/OpenShape_code/blob/26cf8d16551368f8f1e8e3801cbfb629b6157a03/src/data.py#L238C10-L238C19

Basically, to use PointBert, you don't need to process the PC with MinkowskiEngine.

**Comment by Holmes-GU** [comment]
> Hi, please refer to the codes:
> 
> https://github.com/Colin97/OpenShape_code/blob/26cf8d16551368f8f1e8e3801cbfb629b6157a03/src/train.py#L101C18-L101C18
> 
> https://github.com/Colin97/OpenShape_code/blob/26cf8d16551368f8f1e8e3801cbfb629b6157a03/src/data.py#L238C10-L238C19
> 
> Basically, to use PointBert, you don't need to process the PC with MinkowskiEngine.

Ok. Thanks for your instructions. I will try it tomorrow~

**Comment by Holmes-GU** [comment]
Hi. Following your instructions, I successfully run the codes. 

Sorry for bothering you again. I observe some differences in processing data in training and testing as follows:

1. In training, the rgb is multiplied by a factor 0.4 in 'if use_color' from 'class Four'. Why not apply it in testing?
2. In class ModelNet40Test, 'rgb = rgb / 255.0' is applied before 'if use_color' but not applied and observed in 'class ObjaverseLVIS' and 'class ScanObjectNNTest'.

**Comment by Colin97** [comment]
1. Do you mean this [line](https://github.com/Colin97/OpenShape_code/blob/26cf8d16551368f8f1e8e3801cbfb629b6157a03/src/data.py#L67)? This is an augmentation, which randomly change the colors of some shapes to a constant (0.4).

2. This is due to some inconsistency when preparing the data files. RGB in ObjaverseLVIS and ScanObjectNN are in [0,1]. ModelNet40 don't have colors and we put 100 for all data files. 'rgb = rgb / 255.0' is just to normalize them to 0.4.

**Comment by Holmes-GU** [comment]
> 1. line

OK. What about this part? Does ScanObjectNNTest not own colors and directly set it as a constant (0.4)?
<img width="1248" alt="image" src="https://github.com/Colin97/OpenShape_code/assets/55798572/e7f14594-fa39-4237-832d-c09b1f4fe893">

**Comment by Colin97** [comment]
Yes.

**Comment by Holmes-GU** [comment]
> Yes.

OK, thank you very much.

**Comment by Holmes-GU** [comment]
哈喽，再问一下哦，这个地方为啥只取x[:,0],而不是x呢？
<img width="1368" alt="image" src="https://github.com/Colin97/OpenShape_code/assets/55798572/86ec5885-e75e-4cc1-98dc-1ca8c2c35c3c">

**Comment by Holmes-GU** [comment]
> 哈喽，再问一下哦，这个地方为啥只取x[:,0],而不是x呢？
这个x[:,0]是class token吧，然后剩下的384是聚合以后点的个数吧？
> <img alt="image" width="1368" src="https://user-images.githubusercontent.com/55798572/254828261-86ec5885-e75e-4cc1-98dc-1ca8c2c35c3c.png">

**Comment by eliphatfs** [comment]
Because we pick the first token, which is the CLS token, as the pooler output, as in any transformer encoder architecture (including but not limited to BERT, CLIP ViT, PointBERT).
