### ISSUE TITLE
Inquiry about the Objaverse dataset

### ISSUE THREAD

**Issue by shayan-nikoo** [Colin97/OpenShape_code#9]
Thanks for your nice work.

I downloaded Objaverse dataset using your download script. The final files are 185 GB as you mentioned but I can't extract them (attached image). 
- Can you help me with that? 
- If I extract them how much space on the disk do I need? I tried downloading the original Objaverse files it is about 1.2 TB.
- In the Readme you mentioned the `npy` files contain `xyz` (point clouds) of the shape. Did you sample these points on the original `glb` files or these are mesh vertices?
- Could you please add a License, which pre-trained models can we use commercially?

<img width="500" alt="image" src="https://github.com/Colin97/OpenShape_code/assets/123162959/69b29f6b-ab71-4522-8dbf-21b1b8969a18">

**Comment by Colin97** [comment]
Sorry, but I have no idea why the downloaded files look like that. The downloaded file should be in .zip or .tar.gz formats. Is the download finished or aborted? Have you tried manually downloading the data from the website?

It should be less than 1.2TB. About 300GB if I remember correctly.

Yes, we sample the points from the mesh surface.

We add an Apache 2.0 license, and you can use the pre-trained models commercially.

**Comment by shayan-nikoo** [comment]
Thank you Colin for your reply. 
Then if these files are not correct I assume the download was interrupted because I was downloading them on a remote machine. Which website I can download manually? 

When you say download from the website manually, do you mean here?
https://huggingface.co/datasets/OpenShape/openshape-training-data

I don't find any download option.
Thanks for the license.

**Comment by shayan-nikoo** [comment]
The manual download works, I was not logged-in. Thanks.
